version: '3.8'
services:

    database-service:
        image: mysql:8.0
        container_name: database-service
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
        ports:
            - "2401:3306"
        volumes:
            - ./data:/var/lib/mysql
    adminer-service:
        image: adminer
        container_name: adminer-service
        restart: always
        ports:
            - "2402:8080"

    subscription-service:
        container_name: subscription-service
        build:
            context: .
            dockerfile: Dockerfile
        image: laravelapp:latest
        ports:
            - "2403:80"
        volumes:
            - ./:/var/www/html
        env_file:
            - .env
        depends_on:
            - database-service

volumes:
    data:
        driver: local

networks:
    network-service:
        driver: bridge
