version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravelapp:latest
        ports:
            - "2401:80"
        volumes:
            - ./:/var/www/html
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "2402:3306"
        volumes:
            - data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - "2403:8080"

volumes:
    dbdata:
        driver: local
